[package]
name = "vk_docs_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"

[dependencies.regex]
version = "1.10.4"
features = ["std"]
